package modelo;
// Generated 1 dic 2025, 10:51:08 by Hibernate Tools 6.5.1.Final

import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

import org.hibernate.Session;
import org.hibernate.query.Query;

/**
 * CentrosMeteorologicos generated by hbm2java
 */
public class CentrosMeteorologicos implements java.io.Serializable {

	private Integer idCentroMet;
	private Municipios municipios;
	private String nombre;
	private String direccion;
	private Double latitud;
	private Double longitud;
	private String url;
	private String hash;
	private Set medicionesCentroMets = new HashSet(0);

	public CentrosMeteorologicos() {
	}

	public CentrosMeteorologicos(Municipios municipios, String nombre, String direccion, Double latitud,
			Double longitud, String url, String hash, Set medicionesCentroMets) {
		this.municipios = municipios;
		this.nombre = nombre;
		this.direccion = direccion;
		this.latitud = latitud;
		this.longitud = longitud;
		this.url = url;
		this.hash = hash;
		this.medicionesCentroMets = medicionesCentroMets;
	}

	public Integer getIdCentroMet() {
		return this.idCentroMet;
	}

	public void setIdCentroMet(Integer idCentroMet) {
		this.idCentroMet = idCentroMet;
	}

	public Municipios getMunicipios() {
		return this.municipios;
	}

	public void setMunicipios(Municipios municipios) {
		this.municipios = municipios;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getDireccion() {
		return this.direccion;
	}

	public void setDireccion(String direccion) {
		this.direccion = direccion;
	}

	public Double getLatitud() {
		return this.latitud;
	}

	public void setLatitud(Double latitud) {
		this.latitud = latitud;
	}

	public Double getLongitud() {
		return this.longitud;
	}

	public void setLongitud(Double longitud) {
		this.longitud = longitud;
	}

	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	public String getHash() {
		return this.hash;
	}

	public void setHash(String hash) {
		this.hash = hash;
	}

	public Set getMedicionesCentroMets() {
		return this.medicionesCentroMets;
	}

	public void setMedicionesCentroMets(Set medicionesCentroMets) {
		this.medicionesCentroMets = medicionesCentroMets;
	}
	
	public static ArrayList<CentrosMeteorologicos> obtenerListaCentrosMunicipio(Session session, Municipios municipio) {
	    ArrayList<CentrosMeteorologicos> listaCentros = new ArrayList<>();
		String hql = "from CentrosMeteorologicos where municipios = :municipio";
		Query<CentrosMeteorologicos> q = session.createQuery(hql, CentrosMeteorologicos.class);
		q.setParameter("municipio", municipio);
		List<CentrosMeteorologicos> filas = q.list();
		for (int i = 0; i < filas.size(); i++) {
			CentrosMeteorologicos c = (CentrosMeteorologicos) filas.get(i);
			listaCentros.add(c);
		}
		return listaCentros;
	}
	public void obtenerCentroPorNombreYMunicipio(Session session, String nombreCentro, Municipios municipio) {
	    String hql = "from CentrosMeteorologicos where nombre = :nombreCentro and municipios = :municipio";
	    Query<CentrosMeteorologicos> q = session.createQuery(hql, CentrosMeteorologicos.class);
	    q.setParameter("nombreCentro", nombreCentro);
	    q.setParameter("municipio", municipio);
	    CentrosMeteorologicos centro = q.uniqueResult();
	    if (centro != null) {
	        this.idCentroMet = centro.getIdCentroMet();
	        this.municipios = centro.getMunicipios();
	        this.nombre = centro.getNombre();
	        this.direccion = centro.getDireccion();
	        this.latitud = centro.getLatitud();
	        this.longitud = centro.getLongitud();
	        this.url = centro.getUrl();
	        this.hash = centro.getHash();
	        this.medicionesCentroMets = centro.getMedicionesCentroMets();
	    }
	}

}
