package modelo;
// Generated 1 dic 2025, 10:51:08 by Hibernate Tools 6.5.1.Final

import java.sql.Date;
import java.sql.Time;

import com.google.gson.annotations.Expose;

/**
 * MedicionesCentroMetId generated by hbm2java
 */
public class MedicionesCentroMetId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	@Expose
	private Date fecha;
	@Expose
	private Time hora;
	@Expose
	private int idCentroMet;

	public MedicionesCentroMetId() {
	}

	public MedicionesCentroMetId(Date fecha, Time hora, int idCentroMet) {
		this.fecha = fecha;
		this.hora = hora;
		this.idCentroMet = idCentroMet;
	}

	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	public Time getHora() {
		return this.hora;
	}

	public void setHora(Time hora) {
		this.hora = hora;
	}

	public int getIdCentroMet() {
		return this.idCentroMet;
	}

	public void setIdCentroMet(int idCentroMet) {
		this.idCentroMet = idCentroMet;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof MedicionesCentroMetId))
			return false;
		MedicionesCentroMetId castOther = (MedicionesCentroMetId) other;

		return ((this.getFecha() == castOther.getFecha()) || (this.getFecha() != null && castOther.getFecha() != null
				&& this.getFecha().equals(castOther.getFecha())))
				&& ((this.getHora() == castOther.getHora()) || (this.getHora() != null && castOther.getHora() != null
						&& this.getHora().equals(castOther.getHora())))
				&& (this.getIdCentroMet() == castOther.getIdCentroMet());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getFecha() == null ? 0 : this.getFecha().hashCode());
		result = 37 * result + (getHora() == null ? 0 : this.getHora().hashCode());
		result = 37 * result + this.getIdCentroMet();
		return result;
	}
}
