package modelo;

import java.util.ArrayList;
import java.util.List;

import org.hibernate.Session;
import org.hibernate.query.Query;

import com.google.gson.annotations.Expose;

// Generated 1 dic 2025, 10:51:08 by Hibernate Tools 6.5.1.Final

/**
 * MedicionesCentroMet generated by hbm2java
 */
public class MedicionesCentroMet implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	@Expose
	private MedicionesCentroMetId id;
	@Expose
	private CentrosMeteorologicos centrosMeteorologicos;
	@Expose
	private Integer dirViento;
	@Expose
	private Integer HRelativa;
	@Expose
	private Float PAtmosferica;
	@Expose
	private Float precip;
	@Expose
	private Float radSolar;
	@Expose
	private Float tempAmbiente;
	@Expose
	private Float VViento;
	@Expose
	private String ica;

	public MedicionesCentroMet() {
	}

	public MedicionesCentroMet(MedicionesCentroMetId id, CentrosMeteorologicos centrosMeteorologicos) {
		this.id = id;
		this.centrosMeteorologicos = centrosMeteorologicos;
	}

	public MedicionesCentroMet(MedicionesCentroMetId id, CentrosMeteorologicos centrosMeteorologicos, Integer dirViento,
			Integer HRelativa, Float PAtmosferica, Float precip, Float radSolar, Float tempAmbiente, Float VViento,
			String ica) {
		this.id = id;
		this.centrosMeteorologicos = centrosMeteorologicos;
		this.dirViento = dirViento;
		this.HRelativa = HRelativa;
		this.PAtmosferica = PAtmosferica;
		this.precip = precip;
		this.radSolar = radSolar;
		this.tempAmbiente = tempAmbiente;
		this.VViento = VViento;
		this.ica = ica;
	}

	public MedicionesCentroMetId getId() {
		return this.id;
	}

	public void setId(MedicionesCentroMetId id) {
		this.id = id;
	}

	public CentrosMeteorologicos getCentrosMeteorologicos() {
		return this.centrosMeteorologicos;
	}

	public void setCentrosMeteorologicos(CentrosMeteorologicos centrosMeteorologicos) {
		this.centrosMeteorologicos = centrosMeteorologicos;
	}

	public Integer getDirViento() {
		return this.dirViento;
	}

	public void setDirViento(Integer dirViento) {
		this.dirViento = dirViento;
	}

	public Integer getHRelativa() {
		return this.HRelativa;
	}

	public void setHRelativa(Integer HRelativa) {
		this.HRelativa = HRelativa;
	}

	public Float getPAtmosferica() {
		return this.PAtmosferica;
	}

	public void setPAtmosferica(Float PAtmosferica) {
		this.PAtmosferica = PAtmosferica;
	}

	public Float getPrecip() {
		return this.precip;
	}

	public void setPrecip(Float precip) {
		this.precip = precip;
	}

	public Float getRadSolar() {
		return this.radSolar;
	}

	public void setRadSolar(Float radSolar) {
		this.radSolar = radSolar;
	}

	public Float getTempAmbiente() {
		return this.tempAmbiente;
	}

	public void setTempAmbiente(Float tempAmbiente) {
		this.tempAmbiente = tempAmbiente;
	}

	public Float getVViento() {
		return this.VViento;
	}

	public void setVViento(Float VViento) {
		this.VViento = VViento;
	}

	public String getIca() {
		return this.ica;
	}

	public void setIca(String ica) {
		this.ica = ica;
	}
	public static ArrayList<MedicionesCentroMet> obtenerListaMedicionesCentroMet(org.hibernate.Session session, int idCentroMet) {
		String hql = "from MedicionesCentroMet where centrosMeteorologicos.idCentroMet = :idCentroMet";
		Query<MedicionesCentroMet> query = session.createQuery(hql, MedicionesCentroMet.class);
		query.setParameter("idCentroMet", idCentroMet);
		List<MedicionesCentroMet> resultados = query.list();
		return new ArrayList<MedicionesCentroMet>(resultados);
	}

	public static ArrayList<MedicionesCentroMet> obtenerListaMediciones(Session session) {
		ArrayList<MedicionesCentroMet> lista = new ArrayList<>();
		String hql = "from MedicionesCentroMet";
		Query<MedicionesCentroMet> q = session.createQuery(hql, MedicionesCentroMet.class);
		List<MedicionesCentroMet> filas = q.list();
		for (int i = 0; i < filas.size(); i++) {
			MedicionesCentroMet p = (MedicionesCentroMet) filas.get(i);
			lista.add(p);
		}
		return lista;
		}
	
}
