package modelo;

import com.google.gson.annotations.Expose;

// Generated 1 dic 2025, 10:51:08 by Hibernate Tools 6.5.1.Final

/**
 * MunicipiosEspaciosNat generated by hbm2java
 */
public class MunicipiosEspaciosNat implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	@Expose
	private MunicipiosEspaciosNatId id;
	@Expose
	private EspaciosNaturales espaciosNaturales;
	@Expose
	private Municipios municipios;

	public MunicipiosEspaciosNat() {
	}

	public MunicipiosEspaciosNat(MunicipiosEspaciosNatId id, EspaciosNaturales espaciosNaturales,
			Municipios municipios) {
		this.id = id;
		this.espaciosNaturales = espaciosNaturales;
		this.municipios = municipios;
	}

	public MunicipiosEspaciosNatId getId() {
		return this.id;
	}

	public void setId(MunicipiosEspaciosNatId id) {
		this.id = id;
	}

	public EspaciosNaturales getEspaciosNaturales() {
		return this.espaciosNaturales;
	}

	public void setEspaciosNaturales(EspaciosNaturales espaciosNaturales) {
		this.espaciosNaturales = espaciosNaturales;
	}

	public Municipios getMunicipios() {
		return this.municipios;
	}

	public void setMunicipios(Municipios municipios) {
		this.municipios = municipios;
	}

}
