package modelo;
// Generated 1 dic 2025, 10:51:08 by Hibernate Tools 6.5.1.Final

import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

import org.hibernate.Session;
import org.hibernate.query.Query;
/**
 * Provincias generated by hbm2java
 */
public class Provincias implements java.io.Serializable {

	private int idProvincia;
	private String nombre;
	private Set municipioses = new HashSet(0);

	public Provincias() {
	}

	public Provincias(int idProvincia) {
		this.idProvincia = idProvincia;
	}

	public Provincias(int idProvincia, String nombre, Set municipioses) {
		this.idProvincia = idProvincia;
		this.nombre = nombre;
		this.municipioses = municipioses;
	}

	public int getIdProvincia() {
		return this.idProvincia;
	}

	public void setIdProvincia(int idProvincia) {
		this.idProvincia = idProvincia;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public Set getMunicipioses() {
		return this.municipioses;
	}

	public void setMunicipioses(Set municipioses) {
		this.municipioses = municipioses;
	}
	
	public static ArrayList<Provincias> obtenerListaProvincias(Session session) {
	    ArrayList<Provincias> listaProvincias = new ArrayList<>();
		String hql = "from Provincias";
		Query<Provincias> q = session.createQuery(hql, Provincias.class);
		List<Provincias> filas = q.list();
		for (int i = 0; i < filas.size(); i++) {
			Provincias p = (Provincias) filas.get(i);
			listaProvincias.add(p);
		}
		return listaProvincias;

	}
	public void obtenerProvinciaPorNombre(Session session, String nombreProvincia) {
	    String hql = "from Provincias where nombre = :nombreProvincia";
	    Query<Provincias> q = session.createQuery(hql, Provincias.class);
	    q.setParameter("nombreProvincia", nombreProvincia);
	    Provincias provincia = q.uniqueResult();
	    if (provincia != null) {
	        this.idProvincia = provincia.getIdProvincia();
	        this.nombre = provincia.getNombre();
	        this.municipioses = provincia.getMunicipioses();
	    }
	}
}
