package modelo;
// Generated 13 ene 2026, 8:47:05 by Hibernate Tools 6.5.1.Final

import java.util.HashSet;
import java.util.Set;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * Ciclos generated by hbm2java
 */
public class Ciclos implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer id;
	private String nombre;
	@JsonIgnore
	private Set<Modulos> moduloses = new HashSet<Modulos>(0);
	@JsonIgnore
	private Set<Matriculaciones> matriculacioneses = new HashSet<Matriculaciones>(0);

	public Ciclos() {
	}

	public Ciclos(String nombre) {
		this.nombre = nombre;
	}

	public Ciclos(String nombre, Set<Modulos> moduloses, Set<Matriculaciones> matriculacioneses) {
		this.nombre = nombre;
		this.moduloses = moduloses;
		this.matriculacioneses = matriculacioneses;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public Set<Modulos>  getModuloses() {
		return this.moduloses;
	}

	public void setModuloses(Set<Modulos> moduloses) {
		this.moduloses = moduloses;
	}

	public Set<Matriculaciones> getMatriculacioneses() {
		return this.matriculacioneses;
	}

	public void setMatriculacioneses(Set<Matriculaciones> matriculacioneses) {
		this.matriculacioneses = matriculacioneses;
	}

}
