package modelo;
// Generated 13 ene 2026, 8:47:05 by Hibernate Tools 6.5.1.Final

import java.util.HashSet;
import java.util.Set;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * Modulos generated by hbm2java
 */
public class Modulos implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private Integer id;
	private Ciclos ciclos;
	private String nombre;
	private String nombreEus;
	private int horas;
	private byte curso;
	@JsonIgnore
	private Set<Horarios> horarioses = new HashSet<Horarios>(0);

	public Modulos() {
	}

	public Modulos(Ciclos ciclos, String nombre, int horas, byte curso) {
		this.ciclos = ciclos;
		this.nombre = nombre;
		this.horas = horas;
		this.curso = curso;
	}

	public Modulos(Modulos otro) {
	    this.ciclos = otro.getCiclos() != null ? new Ciclos(otro.getCiclos().getNombre()) : null;
	    if (this.ciclos != null) {
	        this.ciclos.setId(otro.getCiclos().getId());
	    }
	    this.nombre = otro.getNombre();
	    this.nombreEus = otro.getNombreEus();
	    this.horas = otro.getHoras();
	    this.curso = otro.getCurso();
	}
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Ciclos getCiclos() {
		return this.ciclos;
	}

	public void setCiclos(Ciclos ciclos) {
		this.ciclos = ciclos;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getNombreEus() {
		return this.nombreEus;
	}

	public void setNombreEus(String nombreEus) {
		this.nombreEus = nombreEus;
	}

	public int getHoras() {
		return this.horas;
	}

	public void setHoras(int horas) {
		this.horas = horas;
	}

	public byte getCurso() {
		return this.curso;
	}

	public void setCurso(byte curso) {
		this.curso = curso;
	}

	public Set<Horarios> getHorarioses() {
		return this.horarioses;
	}

	public void setHorarioses(Set<Horarios> horarioses) {
		this.horarioses = horarioses;
	}


}
