package modelo;
// Generated 13 ene 2026, 8:47:05 by Hibernate Tools 6.5.1.Final

import java.sql.Timestamp;
import java.time.DayOfWeek;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;

import org.hibernate.Session;
import org.hibernate.SessionFactory;
import org.hibernate.query.Query;
import org.hibernate.Transaction;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.reto2.elorserv.HibernateUtil;

/**
 * Reuniones generated by hbm2java
 */
public class Reuniones implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer idReunion;
	private Users usersByAlumnoId;
	private Users usersByProfesorId;
	private String estado;
	private String estadoEus;
	private String idCentro;
	private String titulo;
	private String asunto;
	private String aula;
	private Timestamp fecha;
	private Timestamp createdAt;
	private Timestamp updatedAt;
	private Centros centro;

	public enum EstadoReunion {
		PENDIENTE("pendiente"),
		ACEPTADA("aceptada"),
		DENEGADA("denegada"),
		CONFLICTO("conflicto");

		private final String value;

		EstadoReunion(String value) {
			this.value = value;
		}

		public String getValue() {
			return value;
		}
		
		public String getValueEus() {
			switch (this) {
				case PENDIENTE: return "onartzeke";
				case ACEPTADA: return "onartuta";
				case DENEGADA: return "ezeztatuta";
				case CONFLICTO: return "gatazka";
				default: return "onartzeke";
			}
		}

		public static EstadoReunion fromValue(String value) {
			if (value == null || value.isBlank()) {
				return null;
			}
			for (EstadoReunion estado : values()) {
				if (estado.value.equalsIgnoreCase(value)) {
					return estado;
				}
			}
			throw new IllegalArgumentException("Estado de reunión desconocido: " + value);
		}
	}

	public EstadoReunion getEstadoEnum() {
		return EstadoReunion.fromValue(this.estado);
	}
	public Reuniones() {
	}

	public Reuniones(int idReunion) {
		this.idReunion = idReunion;
	}

	public Reuniones(Users usersByAlumnoId, Users usersByProfesorId, String estado, String estadoEus, String idCentro,
			String titulo, String asunto, String aula, Timestamp fecha, Timestamp createdAt, Timestamp updatedAt) {
		this.usersByAlumnoId = usersByAlumnoId;
		this.usersByProfesorId = usersByProfesorId;
		this.estado = estado;
		this.estadoEus = estadoEus;
		this.idCentro = idCentro;
		this.titulo = titulo;
		this.asunto = asunto;
		this.aula = aula;
		this.fecha = fecha;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
	}

	public Reuniones(Reuniones otro) {
	    this.idReunion = otro.getIdReunion();
	    this.usersByAlumnoId = otro.getUsersByAlumnoId() != null ? new Users(otro.getUsersByAlumnoId()) : null;
	    this.usersByProfesorId = otro.getUsersByProfesorId() != null ? new Users(otro.getUsersByProfesorId()) : null;
	    this.estado = otro.getEstado();
	    this.estadoEus = otro.getEstadoEus();
	    this.idCentro = otro.getIdCentro();
	    this.titulo = otro.getTitulo();
	    this.asunto = otro.getAsunto();
	    this.aula = otro.getAula();
	    this.fecha = otro.getFecha();
	    this.createdAt = otro.getCreatedAt();
	    this.updatedAt = otro.getUpdatedAt();
	    // Carga el centro asociado desde el Json
	    this.centro = new Centros(Integer.parseInt(this.idCentro)).getCentroById();
	}

	public Integer getIdReunion() {
		return this.idReunion;
	}

	public void setIdReunion(Integer idReunion) {
		this.idReunion = idReunion;
	}

	public Users getUsersByAlumnoId() {
		return this.usersByAlumnoId;
	}

	public void setUsersByAlumnoId(Users usersByAlumnoId) {
		this.usersByAlumnoId = usersByAlumnoId;
	}

	public Users getUsersByProfesorId() {
		return this.usersByProfesorId;
	}

	public void setUsersByProfesorId(Users usersByProfesorId) {
		this.usersByProfesorId = usersByProfesorId;
	}

	public String getEstado() {
		return this.estado;
	}


	public void setEstado(String estado) {
		this.estado = estado;
	}

	public void setEstado(EstadoReunion estadoEnum) {
		if (estadoEnum != null) {
			this.estado = estadoEnum.getValue();
			this.estadoEus = estadoEnum.getValueEus();
		} else {
			this.estado = null;
			this.estadoEus = null;
		}
	}

	public String getEstadoEus() {
		return this.estadoEus;
	}

	public void setEstadoEus(String estadoEus) {
		// Prevenir que se establezca un string vacío
		if (estadoEus != null && estadoEus.trim().isEmpty()) {
			this.estadoEus = null;
		} else {
			this.estadoEus = estadoEus;
		}
	}

	public String getIdCentro() {
		return this.idCentro;
	}

	public void setIdCentro(String idCentro) {
		this.idCentro = idCentro;
	}

	public String getTitulo() {
		return this.titulo;
	}

	public void setTitulo(String titulo) {
		this.titulo = titulo;
	}

	public String getAsunto() {
		return this.asunto;
	}

	public void setAsunto(String asunto) {
		this.asunto = asunto;
	}

	public String getAula() {
		return this.aula;
	}

	public void setAula(String aula) {
		this.aula = aula;
	}

	public Timestamp getFecha() {
		return this.fecha;
	}

	public void setFecha(Timestamp fecha) {
		this.fecha = fecha;
	}
	
	public void setFecha(String fechaStr) {
		if (fechaStr != null && !fechaStr.isBlank()) {
			try {
				// Si viene solo la fecha (YYYY-MM-DD), agregar hora por defecto
				if (fechaStr.length() == 10) {
					fechaStr = fechaStr + " 00:00:00";
				}
				this.fecha = Timestamp.valueOf(fechaStr);
			} catch (Exception e) {
				throw new IllegalArgumentException("Formato de fecha inválido: " + fechaStr);
			}
		}
	}

	public Timestamp getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Timestamp createdAt) {
		this.createdAt = createdAt;
	}

	public Timestamp getUpdatedAt() {
		return this.updatedAt;
	}
	
	public void setUpdatedAt(Timestamp updatedAt) {
		this.updatedAt = updatedAt;
	}
	public Centros getCentro() {
		return this.centro;
	}

	public void setCentro(Centros centro) {
		this.centro = centro;
	}
	




	/**
	 * Recupera todas las reuniones en la base de datos .
	 */
	@JsonIgnore
	public static List<Reuniones> getAllReuniones() {
		SessionFactory sesion = HibernateUtil.getSessionFactory();
		try (Session session = sesion.openSession()) {
			String hql = "from Reuniones";
			Query<Reuniones> q = session.createQuery(hql, Reuniones.class);
			q.list().replaceAll(reunion -> new Reuniones(reunion));
			return q.list();
		}
	}

	/**
	 * Recupera las reuniones en las que participa un usuario dado (como alumno o profesor).
	 */
	public static List<Reuniones> getReunionesByUserID(int idUser) {
		SessionFactory sesion = HibernateUtil.getSessionFactory();
		try (Session session = sesion.openSession()) {
			String hql = "from Reuniones where usersByAlumnoId = "+ idUser + " or usersByProfesorId = "+idUser;
			Query<Reuniones> q = session.createQuery(hql, Reuniones.class);
			// Necesario para devolver el centro referenciado en Angular y ElorEs
			ArrayList<Reuniones> reuniones = new ArrayList<>();
			for (Reuniones reunion : q.list()) {
				reuniones.add(new Reuniones(reunion));
			}
			return reuniones;
		}
	}
	/**
	 * Recupera las reuniones de la semana actual para un usuario específico.
	 */
	public static List<Reuniones> getReunionesByUserIDSemanaActual(int idUser) {
		LocalDate hoy = LocalDate.now();
		LocalDate inicioSemana = hoy.with(DayOfWeek.MONDAY);
		LocalDate finSemana = inicioSemana.plusDays(7);

		Timestamp inicio = Timestamp.valueOf(inicioSemana.atStartOfDay());
		Timestamp fin = Timestamp.valueOf(finSemana.atStartOfDay());

		SessionFactory sesion = HibernateUtil.getSessionFactory();
		try (Session session = sesion.openSession()) {
			String hql = "from Reuniones where (usersByAlumnoId = "+idUser+ " or usersByProfesorId = "+ idUser+") "
					+ "and fecha >= :inicioSemana and fecha < :finSemana order by fecha";
			Query<Reuniones> q = session.createQuery(hql, Reuniones.class);
			q.setParameter("inicioSemana", inicio);
			q.setParameter("finSemana", fin);
			q.list().replaceAll(reunion -> new Reuniones(reunion));
			return q.list();
		}
	}

	/**
	 * Comprueba si la reunión entra en conflicto con la agenda del profesor
	 */
	private boolean hayConflictoConAgendaProfesor() {
		List<Horarios> horariosProfesor = Horarios.getHorariosByUserId(getUsersByProfesorId().getId());
		if (horariosProfesor != null) {
			for (Horarios horario : horariosProfesor) {
				if (horario.coincide(getFecha())) {
					return true;
				}
			}
		}
		List<Reuniones> reunionesProfesor = obtenerReunionesEnDia(getUsersByProfesorId(), getFecha());
		if (reunionesProfesor != null) {
			LocalDateTime nuevaFecha = getFecha().toLocalDateTime();
			for (Reuniones reunionExistente : reunionesProfesor) {
				EstadoReunion estadoExistente = reunionExistente.getEstadoEnum();
				if (estadoExistente == EstadoReunion.DENEGADA) {
					continue;
				}
				if (coincide(nuevaFecha)) {
					return true;
				}
			}
		}
		return false;
	}

	/**
	 * Obtiene las reuniones de un profesor en el día especificado.
	 */
	private static List<Reuniones> obtenerReunionesEnDia(Users profesor, Timestamp fechaReferencia) {
		SessionFactory sesion = HibernateUtil.getSessionFactory();
		try (Session session = sesion.openSession()) {
			LocalDate fecha = fechaReferencia.toLocalDateTime().toLocalDate();
			Timestamp inicioDia = Timestamp.valueOf(fecha.atStartOfDay());
			Timestamp finDia = Timestamp.valueOf(fecha.plusDays(1).atStartOfDay());
			String hql = "from Reuniones where usersByProfesorId = :profesor and fecha >= :inicioDia and fecha < :finDia";
			return session.createQuery(hql, Reuniones.class)
					.setParameter("profesor", profesor)
					.setParameter("inicioDia", inicioDia)
					.setParameter("finDia", finDia)
					.list();
		}
	}

	/**
	 * Comprueba si la nueva fecha coincide con la hora de la reunión actual.
	 */
	private  boolean coincide(LocalDateTime nuevaFecha) {
		if (!nuevaFecha.toLocalDate().equals(getFecha().toLocalDateTime().toLocalDate())) {
			return false;
		}
		return nuevaFecha.getHour() == getFecha().toLocalDateTime().getHour();
	}



	/**
	 * Crea la reunión en la base de datos. Comprueba conflictos con la agenda del profesor
	 * y marca el estado apropiado antes de guardar.
	 */
	public Reuniones crearReunion() {
		// Validaciones
		if (getUsersByAlumnoId() == null || getUsersByAlumnoId().getId() == null) {
			throw new IllegalArgumentException("El alumno es obligatorio para crear una reunión");
		}
		if (getUsersByProfesorId() == null || getUsersByProfesorId().getId() == null) {
			throw new IllegalArgumentException("El profesor es obligatorio para crear una reunión");
		}
		if (getFecha() == null) {
			throw new IllegalArgumentException("La fecha es obligatoria para crear una reunión");
		}
		
		// Importante: el ID debe ser null para crear una nueva entidad
		setIdReunion(null);
		
		SessionFactory sesion = HibernateUtil.getSessionFactory();
		Transaction tx = null;
		try (Session session = sesion.openSession()) {
			tx = session.beginTransaction();
			
			// Usar la sesión actual para cargar los usuarios desde la BD
			Users alumno = session.get(Users.class, getUsersByAlumnoId().getId());
			Users profesor = session.get(Users.class, getUsersByProfesorId().getId());
			
			if (alumno == null) {
				throw new IllegalArgumentException("No se encontró el alumno con ID: " + getUsersByAlumnoId().getId());
			}
			if (profesor == null) {
				throw new IllegalArgumentException("No se encontró el profesor con ID: " + getUsersByProfesorId().getId());
			}
			
			setUsersByAlumnoId(alumno);
			setUsersByProfesorId(profesor);
			Timestamp now = new Timestamp(System.currentTimeMillis());
			if (getCreatedAt() == null) {
				setCreatedAt(now);
			}
			setUpdatedAt(now);
			
			boolean hayConflicto = hayConflictoConAgendaProfesor();
			if (hayConflicto) {
				setEstado(EstadoReunion.CONFLICTO);
			} else if (getEstadoEnum() == null) {
				setEstado(EstadoReunion.PENDIENTE);
			} else {
				// Si ya tiene un estado pero estadoEus está vacío, establecerlo
				if (getEstadoEus() == null || getEstadoEus().trim().isEmpty()) {
					setEstadoEus(getEstadoEnum().getValueEus());
				}
			}
			
			session.persist(this);
			tx.commit();
			return new Reuniones(this);
		} catch (IllegalArgumentException e) {
			if (tx != null) {
				tx.rollback();
			}
			throw e;
		} catch (Exception e) {
			System.out.println("Error en crearReunion: " + e.getMessage());
			e.printStackTrace();
			if (tx != null) {
				tx.rollback();
			}
			throw new RuntimeException("Error al crear la reunión: " + e.getMessage(), e);
		}
	}

	/**
	 * Cambia el estado de una reunión guardada.
	 */
	public Reuniones cambiarEstadoReunion(EstadoReunion nuevoEstado) {
		if (getIdReunion() == null) {
			throw new IllegalStateException("Id de reunión obligatorio para actualizar estado");
		}
		if (nuevoEstado == null) {
			throw new IllegalArgumentException("El nuevo estado no puede ser nulo");
		}
		SessionFactory sesion = HibernateUtil.getSessionFactory();
		Transaction tx = null;
		try (Session session = sesion.openSession()) {
			tx = session.beginTransaction();
			Reuniones reunion = session.get(Reuniones.class, getIdReunion());
			if (reunion == null) {
				throw new RuntimeException("Reunión no encontrada con id: " + getIdReunion());
			}
			reunion.setEstado(nuevoEstado);
			reunion.setUpdatedAt(new Timestamp(System.currentTimeMillis()));
			session.merge(reunion);
			tx.commit();
			return new Reuniones(reunion);
		} catch (Exception e) {
			if (tx != null) {
				tx.rollback();
			}
			throw e;
		}
	}

    /**
     * Elimina la reunión identificada por este objeto.
     */
    public void eliminarReunion() {
        if (getIdReunion() == null) {
            throw new IllegalStateException("Id de reunión obligatorio para eliminar");
        }
        SessionFactory sesion = HibernateUtil.getSessionFactory();
        Transaction tx = null;
        try (Session session = sesion.openSession()) {
            tx = session.beginTransaction();
            Reuniones reunion = session.get(Reuniones.class, getIdReunion());
            if (reunion == null) {
                throw new RuntimeException("Reunión no encontrada con id: " + getIdReunion());
            }
            session.remove(reunion);
            tx.commit();
        } catch (Exception e) {
            if (tx != null) {
                tx.rollback();
            }
            throw e;
        }
    }
}
