package modelo;
// Generated 12 feb 2026, 10:14:36 by Hibernate Tools 6.5.1.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Compositor generated by hbm2java
 */
public class Compositor implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer idCompo;
	private String nomCompo;
	private String naceCompo;
	private String muereCompo;
	private Set<Musica> musicas = new HashSet<Musica>(0);
	public Compositor() {
	}
	public Compositor(int id) {
		this.idCompo = id;
	}

	public Compositor(String nomCompo) {
		this.nomCompo = nomCompo;
	}

	public Compositor(String nomCompo, String naceCompo, String muereCompo, Set<Musica> musicas) {
		this.nomCompo = nomCompo;
		this.naceCompo = naceCompo;
		this.muereCompo = muereCompo;
		this.musicas = musicas;
	}

	public Integer getIdCompo() {
		return this.idCompo;
	}

	public void setIdCompo(Integer idCompo) {
		this.idCompo = idCompo;
	}

	public String getNomCompo() {
		return this.nomCompo;
	}

	public void setNomCompo(String nomCompo) {
		this.nomCompo = nomCompo;
	}

	public String getNaceCompo() {
		return this.naceCompo;
	}

	public void setNaceCompo(String naceCompo) {
		this.naceCompo = naceCompo;
	}

	public String getMuereCompo() {
		return this.muereCompo;
	}

	public void setMuereCompo(String muereCompo) {
		this.muereCompo = muereCompo;
	}

	public Set<Musica> getMusicas() {
		return this.musicas;
	}

	public void setMusicas(Set<Musica> musicas) {
		this.musicas = musicas;
	}

}
