package modelo;
// Generated 12 feb 2026, 10:14:36 by Hibernate Tools 6.5.1.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Estilo generated by hbm2java
 */
public class Estilo implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer idEstilo;
	private String nomEstilo;
	private Set<Musica> musicas = new HashSet<Musica>(0);

	public Estilo() {
	}

	public Estilo(String nomEstilo) {
		this.nomEstilo = nomEstilo;
	}

	public Estilo(String nomEstilo, Set<Musica> musicas) {
		this.nomEstilo = nomEstilo;
		this.musicas = musicas;
	}

	public Estilo(int id) {
		this.idEstilo= id;
	}

	public Integer getIdEstilo() {
		return this.idEstilo;
	}

	public void setIdEstilo(Integer idEstilo) {
		this.idEstilo = idEstilo;
	}

	public String getNomEstilo() {
		return this.nomEstilo;
	}

	public void setNomEstilo(String nomEstilo) {
		this.nomEstilo = nomEstilo;
	}

	public Set<Musica> getMusicas() {
		return this.musicas;
	}

	public void setMusicas(Set<Musica> musicas) {
		this.musicas = musicas;
	}

}
