package modelo;
// Generated 12 feb 2026, 10:14:36 by Hibernate Tools 6.5.1.Final

import java.util.List;

import org.hibernate.Session;
import org.hibernate.SessionFactory;
import org.hibernate.Transaction;
import org.hibernate.query.Query;

/**
 * Musica generated by hbm2java
 */
public class Musica implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer idMusica;
	private Compositor compositor;
	private Estilo estilo;
	private String descMusica;

	public Musica() {
	}

	public Musica(Compositor compositor, Estilo estilo, String descMusica) {
		this.compositor = compositor;
		this.estilo = estilo;
		this.descMusica = descMusica;
	}

	public Integer getIdMusica() {
		return this.idMusica;
	}

	public void setIdMusica(Integer idMusica) {
		this.idMusica = idMusica;
	}

	public Compositor getCompositor() {
		return this.compositor;
	}

	public void setCompositor(Compositor compositor) {
		this.compositor = compositor;
	}

	public Estilo getEstilo() {
		return this.estilo;
	}

	public void setEstilo(Estilo estilo) {
		this.estilo = estilo;
	}

	public String getDescMusica() {
		return this.descMusica;
	}

	public void setDescMusica(String descMusica) {
		this.descMusica = descMusica;
	}
	public void insertar() {
		SessionFactory sesion = HibernateUtil.getSessionFactory();
		Session session = sesion.openSession();
	
		Transaction tx = session.beginTransaction();
		setIdMusica(null);
		session.persist(this);
		tx.commit();
	}
	
	public static List<Musica>  obtenerCompositores1970() {
		SessionFactory sesion = HibernateUtil.getSessionFactory();
		Session session = sesion.openSession();
	    String hql = "from Musica where compositor.naceCompo < 1970 ";
	    Query<Musica> q = session.createQuery(hql, Musica.class);
	    return q.list();
	}
	public static List<Musica>  obtenerOperasMozart() {
		SessionFactory sesion = HibernateUtil.getSessionFactory();
		Session session = sesion.openSession();
	    String hql = "from Musica where estilo.nomEstilo = 'Opera' and compositor.nomCompo = 'Wolfgang Amadeus MOZART' ";
	    Query<Musica> q = session.createQuery(hql, Musica.class);
	    return q.list();
	}

}
